#ifndef DEFINITIONS_CPU_H
#define DEFINITIONS_CPU_H

#include <stdint.h>

#if SIZE_MAX == 0xFFFFU
	#define CPU_ARCHITECTURE_16_BIT
#elif SIZE_MAX == 0xFFFFFFFFU
	#define CPU_ARCHITECTURE_32_BIT
#elif SIZE_MAX == 0xFFFFFFFFFFFFFFFFULL
	#define CPU_ARCHITECTURE_64_BIT
#endif

#if SIZE_MAX >= 0xFFFFU
	#define CPU_ARCHITECTURE_AT_LEAST_16_BIT
#endif
#if SIZE_MAX >= 0xFFFFFFFFU
	#define CPU_ARCHITECTURE_AT_LEAST_32_BIT
#endif
#if SIZE_MAX >= 0xFFFFFFFFFFFFFFFFULL
	#define CPU_ARCHITECTURE_AT_LEAST_64_BIT
#endif

#endif /* DEFINITIONS_CPU_H */