#ifndef DEFINITIONS_CPU_H
#define DEFINITIONS_CPU_H

#include "integer.h"

#if USIZE_MAX == 0xFFFFU
	#define CPU_ARCHITECTURE_16_BIT
#elif USIZE_MAX == 0xFFFFFFFFU
	#define CPU_ARCHITECTURE_32_BIT
#elif USIZE_MAX == 0xFFFFFFFFFFFFFFFFULL
	#define CPU_ARCHITECTURE_64_BIT
#endif

#if USIZE_MAX >= 0xFFFFU
	#define CPU_ARCHITECTURE_AT_LEAST_16_BIT
#endif
#if USIZE_MAX >= 0xFFFFFFFFU
	#define CPU_ARCHITECTURE_AT_LEAST_32_BIT
#endif
#if USIZE_MAX >= 0xFFFFFFFFFFFFFFFFULL
	#define CPU_ARCHITECTURE_AT_LEAST_64_BIT
#endif

#endif /* DEFINITIONS_CPU_H */